"""adicionar multa e data de finalizacao

Revision ID: 0fe401a31fc3
Revises: fb1c7571a296
Create Date: 2026-09-12 13:46:56.712176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe401a31fc3'
down_revision: Union[str, Sequence[str], None] = 'fb1c7571a296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('data_finalizacao', sa.DateTime(), nullable=True))
    op.add_column('pedidos', sa.Column('multa', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'multa')
    op.drop_column('pedidos', 'data_finalizacao')
    # ### end Alembic commands ###
