"""alterado a coluna pagamento

Revision ID: 61f16e6b39b3
Revises: 420b803da4c4
Create Date: 2026-09-12 20:26:10.983379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f16e6b39b3'
down_revision: Union[str, Sequence[str], None] = '420b803da4c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pedidos",
        sa.Column("pagamento", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'pagamento')
    # ### end Alembic commands ###
